@baseUrl = http://localhost:3000

### read phrases 
GET {{baseUrl}}/game

### read suggested phrases
GET {{baseUrl}}/game/readSuggestedPhrases

### add suggested phrase
POST {{baseUrl}}/game/addSuggestedPhrase
Content-Type: application/json

{
    "phrase" : "Je vais te massacrer !"
}

### delete suggested phrase
DELETE {{baseUrl}}/game/deleteSuggestedPhrase/1

### read one suggested phrase
GET {{baseUrl}}/game/readOneSuggestedPhrase/4

### read one phrase
GET {{baseUrl}}/game/readOnePhraseFromGame/23

### add phrase 
POST {{baseUrl}}/game/addPhrase
Content-Type: application/json

{
    "phrase" : "la victoire est mienne !"
}

### remove phrase
DELETE {{baseUrl}}/game/deletePhrase/27